image: Visual Studio 2017
configuration:
  - Debug
  - Release
platform:
  - win32
install:
  - cd %APPVEYOR_BUILD_FOLDER%
  - git submodule update --init --recursive
build:
  project: Outpost2DLL/Outpost2DLL.sln
